### ISSUE TITLE
[N1] - Whitelisted contracts can mint arbitrarily large amounts of debt tokens

### ISSUE THREAD

**Issue by grok13** [Gravita-Protocol/Gravita-SmartContracts#114]
The role of the whitelisted contracts is not completely clear to us. There is only one related comment in DebtToken.sol :                 

<pre class="prettyprint">// stores SC addresses that are allowed to mint/burn the token (AMO strategies, L2 suppliers)
mapping(address => bool) public whitelistedContracts;</pre>

These contracts can mint debt tokens without depositing any collateral calling DebtToken::mintFromWhitelistedContract. This could be a serious problem if such a contract was malicious. Also, even  if these contracts work as expected, minting debt tokens without providing any collateral could have a serious impact on the price of the debt token.

**Comment by grok13** [comment]
We want in the future to  allow selected AMM smart contracts to mint/burn to reduce the volatility of the debtToken (e.g. minting when overpeg and burning when lower)

**Comment by 0xfornax** [comment]
Also, one of our design choices for our L2 future is to allow the creation of contracts that would be able to mint debt tokens and send them to a supported L2. When users borrow on the L2 they would receive these pre-minted tokens instead of minting on the L2 (which would require creating a new token on each L2). This would allow the tokens to be bridged as a single token instance and avoid having multiple ones that would require swapping solutions and cause broken liquidity.

Those future contracts would go through a new round of audits before being deployed and used on the system.
