### ISSUE TITLE
precision loss while calculating redeemedDebtFraction 

### ISSUE THREAD

**Issue by pavankv241** [Gravita-Protocol/Gravita-SmartContracts#274]
**Affected Smart contracts**
VesselManager.sol

**Impact**
precision loss while calculating redeemedDebtFraction  in runtime

**Severity**
Medium because precision loss

**code snippet:-**
https://github.com/Gravita-Protocol/Gravita-SmartContracts/blob/main/contracts/VesselManager.sol#L340

**Reference :-**
https://medium.com/coinmonks/math-in-solidity-part-1-numbers-384c8377f26d 

part 2 ,3 ,4 and 5

**Description :-**
At run time, division in Solidity rounds result towards zero,

```uint256 redeemedDebtFraction = _assetDrawn * _price / _totalDebtTokenSupply;```

the above code may get zero or unintentional result

scenario 1 :-
when product of _assetDrawn and _price  is very small amount than _totalDebtTokenSupply ,result may become zero .

sceanrio 2  :- 
when _totalDebtTokenSupply is large number , result may become zero . 

solidity does not support fractions . 3/11 is always zero in soildity run time .

If _totalDebtTokenSupply as large by supplying large amount of collateral and protocol or user will get unfair amount. 

**Recommedation :-**
 [ADBK library](https://github.com/abdk-consulting/abdk-libraries-solidity) which will handle binary fixed-point and quadruple precision floating-point numbers .
mulDiv() of openzeppelin .

**Comment by 0xfornax** [comment]
We appreciate your report. The function works as intended: upon redemption, the base rate is updated based on a decaying factor and a discount that corresponds to the redeemed debt fraction calc'd from the asset being drawn. Such a fraction can be considered zero if the redeemed amount is insignificant compared to the entire system debt; in that case (and others), the predominant argument for calculating the base rate will instead be the time passed since the last redemption.
